(define (moo)
  (display "string")
  (newline)
  (display #\c)
  (newline)
  (display #t)
  (newline)
  (display (lambda () 1))
  (newline)
  (display 1)
  (newline)
  (display 'symbol)
  (newline)
  (display '())
  (newline)
  (display '(1 2 3))
  (newline)
  (display (cons 'car 'cdr))
  (newline))
  
